"use client";

import { useRef, useState } from "react";
import {
  buildDownloadFilename,
  ErrorCard,
  FilenameField,
  formatBytes,
  ProcessingState,
  SuccessCard,
  UploadCard,
} from "@/components/upload";
import type { UploadPhase } from "@/components/upload";

/** pdf-lib is only needed once the user actually adds or cleans a PDF, so it's dynamically
 *  imported here rather than bundled with every tool page's initial JS — same pattern already
 *  used by PDF Page Extractor, PDF Page Editor, and PDF Splitter. This tool has no visual page
 *  grid, so pdfjs-dist (used for thumbnails elsewhere) isn't needed at all. */
function loadPdfLib() {
  return import("pdf-lib");
}

type PdfLib = Awaited<ReturnType<typeof loadPdfLib>>;

/** The standard PDF Info-dictionary fields pdf-lib exposes getters/setters for, plus whether a
 *  document-level XMP metadata stream is present. This is a read-only snapshot used both for the
 *  "before" inspection and — after cleaning — re-derived from the actual generated bytes rather
 *  than assumed, per the tool's own verification step. */
type MetadataSnapshot = {
  title?: string;
  author?: string;
  subject?: string;
  keywords?: string;
  creator?: string;
  producer?: string;
  creationDate?: Date;
  modificationDate?: Date;
  hasXmp: boolean;
};

type LoadedPdf = {
  file: File;
  pageCount: number;
  pageWidth: number;
  pageHeight: number;
  rotation: number;
  metadata: MetadataSnapshot;
};

type CleanResult = {
  blob: Blob;
  metadata: MetadataSnapshot;
  pageCount: number;
  pageWidth: number;
  pageHeight: number;
  rotation: number;
};

const maxFileSize = 100 * 1024 * 1024;
const defaultFilenameBase = "TinyUtility-Cleaned";

const standardInfoKeys = ["Title", "Author", "Subject", "Keywords", "Creator", "Producer", "CreationDate", "ModDate"];

function toArrayBuffer(bytes: Uint8Array) {
  return bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength) as ArrayBuffer;
}

function isPdfFile(file: File) {
  return file.type === "application/pdf" || file.name.toLowerCase().endsWith(".pdf");
}

function getPdfErrorMessage(error: unknown, pdfLib: PdfLib) {
  if (error instanceof pdfLib.EncryptedPDFError) {
    return "This PDF is password-protected. Remove the password and try again.";
  }

  return "This file couldn't be read. It may be corrupted or not a valid PDF.";
}

function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");

  link.download = filename;
  link.href = url;
  link.click();
  URL.revokeObjectURL(url);
}

/** Reads the current standard metadata straight off a loaded PDFDocument. Loading must have used
 *  `{ updateMetadata: false }` — pdf-lib's default (`true`) rewrites Producer/ModificationDate
 *  (and Creator/CreationDate if absent) the moment the document loads, which would make the
 *  "before" inspection lie about what the file actually contained. */
function readMetadata(pdfDoc: Awaited<ReturnType<PdfLib["PDFDocument"]["load"]>>, pdfLib: PdfLib): MetadataSnapshot {
  return {
    title: pdfDoc.getTitle(),
    author: pdfDoc.getAuthor(),
    subject: pdfDoc.getSubject(),
    keywords: pdfDoc.getKeywords(),
    creator: pdfDoc.getCreator(),
    producer: pdfDoc.getProducer(),
    creationDate: pdfDoc.getCreationDate(),
    modificationDate: pdfDoc.getModificationDate(),
    hasXmp: pdfDoc.catalog.has(pdfLib.PDFName.of("Metadata")),
  };
}

/** Removes the standard Info-dictionary entries and, if present, the document-level XMP metadata
 *  stream — using only pdf-lib's public, documented low-level API (`context`, `PDFDict.delete`,
 *  `PDFName`), never a private/internal method. Deleting these keys is a genuine removal, not
 *  just blanking them to empty strings, and requires no invented API and no fabricated values
 *  (there's no way to set a "removed" Date through pdf-lib's public setters, since they require
 *  a real Date — deleting the underlying key is the correct, honest way to clear it). */
function stripMetadata(pdfDoc: Awaited<ReturnType<PdfLib["PDFDocument"]["load"]>>, pdfLib: PdfLib) {
  const infoRef = pdfDoc.context.trailerInfo.Info;
  const info = infoRef ? pdfDoc.context.lookup(infoRef) : undefined;

  if (info instanceof pdfLib.PDFDict) {
    for (const key of standardInfoKeys) {
      info.delete(pdfLib.PDFName.of(key));
    }
  }

  const metadataKey = pdfLib.PDFName.of("Metadata");
  if (pdfDoc.catalog.has(metadataKey)) {
    pdfDoc.catalog.delete(metadataKey);
  }
}

function formatDate(date: Date | undefined) {
  if (!date) return null;
  try {
    return date.toLocaleString(undefined, { dateStyle: "medium", timeStyle: "short" });
  } catch {
    return null;
  }
}

type MetadataRow = { label: string; value: string | null };

function metadataRows(metadata: MetadataSnapshot): MetadataRow[] {
  return [
    { label: "Title", value: metadata.title || null },
    { label: "Author", value: metadata.author || null },
    { label: "Subject", value: metadata.subject || null },
    { label: "Keywords", value: metadata.keywords || null },
    { label: "Creator", value: metadata.creator || null },
    { label: "Producer", value: metadata.producer || null },
    { label: "Creation Date", value: formatDate(metadata.creationDate) },
    { label: "Modification Date", value: formatDate(metadata.modificationDate) },
  ];
}

function MetadataTable({ metadata, title }: { metadata: MetadataSnapshot; title: string }) {
  return (
    <div>
      <h3 className="text-xs font-semibold uppercase tracking-[0.14em] text-slate-500">{title}</h3>
      <dl className="mt-3 divide-y divide-white/10 overflow-hidden rounded-xl border border-white/10 bg-[#080b1a]/70">
        {metadataRows(metadata).map((row) => (
          <div className="flex flex-col gap-0.5 px-4 py-2.5 sm:flex-row sm:items-baseline sm:justify-between sm:gap-3" key={row.label}>
            <dt className="text-xs font-semibold text-slate-400">{row.label}</dt>
            <dd className={`min-w-0 truncate text-sm ${row.value ? "text-white" : "italic text-slate-500"}`}>
              {row.value ?? "Not set"}
            </dd>
          </div>
        ))}
      </dl>
      <p className="mt-2 text-xs text-slate-500">
        {metadata.hasXmp
          ? "An embedded XMP metadata packet was also detected in this file."
          : "No embedded XMP metadata packet was detected in this file."}
      </p>
    </div>
  );
}

export function PdfMetadataCleanerTool() {
  const downloadedTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const [pdf, setPdf] = useState<LoadedPdf | null>(null);
  const [result, setResult] = useState<CleanResult | null>(null);
  const [filenameBase, setFilenameBase] = useState(defaultFilenameBase);
  const [phase, setPhase] = useState<UploadPhase>("idle");
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [justDownloaded, setJustDownloaded] = useState(false);

  const isBusy = phase === "preparing" || phase === "processing";
  const showSuccessHero = phase === "completed" && result !== null;

  const addFile = async (fileList: FileList | File[]) => {
    const file = Array.from(fileList)[0];

    setResult(null);
    setErrorMessage(null);

    if (!file) return;

    if (!isPdfFile(file)) {
      setPhase("error");
      setErrorMessage("Please choose a PDF file.");
      return;
    }

    if (file.size > maxFileSize) {
      setPhase("error");
      setErrorMessage("The PDF must be 100 MB or smaller.");
      return;
    }

    setPhase("preparing");

    const pdfLib = await loadPdfLib();

    try {
      const bytes = await file.arrayBuffer();
      // updateMetadata: false — otherwise pdf-lib silently rewrites Producer and
      // ModificationDate (and Creator/CreationDate, if absent) the instant the file loads,
      // which would make this "before" snapshot inaccurate.
      const pdfDoc = await pdfLib.PDFDocument.load(bytes, { updateMetadata: false });
      const pageCount = pdfDoc.getPageCount();

      if (pageCount === 0) {
        setPhase("error");
        setErrorMessage("This PDF has no pages.");
        return;
      }

      const firstPage = pdfDoc.getPage(0);
      const { width, height } = firstPage.getSize();
      const rotation = firstPage.getRotation().angle;
      const metadata = readMetadata(pdfDoc, pdfLib);

      setPdf({ file, pageCount, pageWidth: width, pageHeight: height, rotation, metadata });
      setFilenameBase(defaultFilenameBase);
      setPhase("idle");
    } catch (error) {
      setPhase("error");
      setErrorMessage(getPdfErrorMessage(error, pdfLib));
    }
  };

  const clearAll = () => {
    if (downloadedTimeoutRef.current) clearTimeout(downloadedTimeoutRef.current);
    setPdf(null);
    setResult(null);
    setPhase("idle");
    setErrorMessage(null);
    setJustDownloaded(false);
  };

  const backToInspection = () => {
    setResult(null);
    setPhase("idle");
    setJustDownloaded(false);
  };

  const cleanMetadata = async () => {
    if (!pdf) return;

    setPhase("processing");
    setErrorMessage(null);

    const pdfLib = await loadPdfLib();

    try {
      const sourceBytes = await pdf.file.arrayBuffer();
      const pdfDoc = await pdfLib.PDFDocument.load(sourceBytes, { updateMetadata: false });

      stripMetadata(pdfDoc, pdfLib);

      const outputBytes = await pdfDoc.save();
      const blob = new Blob([toArrayBuffer(outputBytes)], { type: "application/pdf" });

      // Don't just assume the write succeeded — reload the actual generated bytes and read
      // back the real resulting state, the same way a user's own PDF reader would see it.
      const verifyDoc = await pdfLib.PDFDocument.load(outputBytes, { updateMetadata: false });
      const verifiedMetadata = readMetadata(verifyDoc, pdfLib);
      const verifiedPageCount = verifyDoc.getPageCount();
      const verifiedFirstPage = verifyDoc.getPage(0);
      const verifiedSize = verifiedFirstPage.getSize();
      const verifiedRotation = verifiedFirstPage.getRotation().angle;

      setResult({
        blob,
        metadata: verifiedMetadata,
        pageCount: verifiedPageCount,
        pageWidth: verifiedSize.width,
        pageHeight: verifiedSize.height,
        rotation: verifiedRotation,
      });
      setPhase("completed");
    } catch (error) {
      setPhase("error");
      setErrorMessage(getPdfErrorMessage(error, pdfLib));
    }
  };

  const markDownloaded = () => {
    setJustDownloaded(true);
    if (downloadedTimeoutRef.current) clearTimeout(downloadedTimeoutRef.current);
    downloadedTimeoutRef.current = setTimeout(() => setJustDownloaded(false), 3000);
  };

  const downloadResult = () => {
    if (!result) return;
    downloadBlob(result.blob, buildDownloadFilename(filenameBase, "pdf", defaultFilenameBase));
    markDownloaded();
  };

  return (
    <section className="mt-16 space-y-6">
      <div className="rounded-2xl border border-teal-300/20 bg-teal-300/10 p-5 text-sm font-medium leading-6 text-teal-100">
        Your PDF never leaves your device. Metadata is inspected and cleared entirely in your browser.
      </div>

      <div className="rounded-2xl border border-white/10 bg-white/[0.03] p-5 text-xs leading-5 text-slate-400">
        This removes the standard document metadata fields shown below (the PDF&apos;s Info dictionary) and
        any embedded XMP metadata packet — the metadata this library can reliably read and clear. It does
        not guarantee removal of every possible embedded object, attachment, annotation, hidden layer, or
        other application-specific data a PDF can contain.
      </div>

      {showSuccessHero && result ? (
        <SuccessCard
          beforeActions={<FilenameField extension="pdf" onChange={setFilenameBase} value={filenameBase} />}
          downloadLabel="Download PDF"
          heroStat={{ label: "Standard fields cleared", value: `${metadataRows(result.metadata).length}` }}
          justDownloaded={justDownloaded}
          onDownload={downloadResult}
          onReset={clearAll}
          resetLabel="Clean Another PDF"
          stats={[
            { label: "Pages", value: `${result.pageCount}` },
            { label: "Dimensions", value: `${Math.round(result.pageWidth)} × ${Math.round(result.pageHeight)} pt` },
            { label: "File size", value: formatBytes(result.blob.size) },
          ]}
          subtitle="Standard metadata was cleared and the result was re-checked below."
          title="Metadata Cleared"
        >
          <button
            className="mx-auto block text-sm font-medium text-teal-300 transition hover:text-teal-100"
            onClick={backToInspection}
            type="button"
          >
            Back to this PDF
          </button>
          <div className="mt-6">
            <MetadataTable metadata={result.metadata} title="Metadata after cleaning (verified from the generated file)" />
          </div>
        </SuccessCard>
      ) : (
        <div className="grid gap-6 lg:grid-cols-[1.3fr_0.7fr]">
          <div className="rounded-3xl border border-white/10 bg-white/[0.04] p-5 shadow-2xl shadow-black/20 sm:p-8">
            {!pdf ? (
              <UploadCard
                accept="application/pdf"
                disabled={isBusy}
                formatsLabel="PDF"
                helperText="Maximum 100 MB. One PDF at a time."
                onFiles={(files) => void addFile(files)}
              />
            ) : (
              <>
                <div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center">
                  <div className="min-w-0">
                    <p className="truncate text-sm font-semibold text-white">{pdf.file.name}</p>
                    <p className="mt-1 text-sm text-slate-400">
                      {pdf.pageCount} page{pdf.pageCount === 1 ? "" : "s"} · {formatBytes(pdf.file.size)}
                    </p>
                  </div>
                  <button
                    className="shrink-0 rounded-full border border-white/15 bg-white/5 px-5 py-2.5 text-sm font-semibold text-slate-200 transition hover:border-white/30 hover:bg-white/10 disabled:cursor-not-allowed disabled:opacity-50"
                    disabled={isBusy}
                    onClick={clearAll}
                    type="button"
                  >
                    Choose a different PDF
                  </button>
                </div>

                <div className="mt-6">
                  <MetadataTable metadata={pdf.metadata} title="Detected metadata" />
                </div>
              </>
            )}
          </div>

          <aside className="space-y-6">
            <div className="rounded-3xl border border-white/10 bg-white/[0.04] p-5 shadow-2xl shadow-black/20 sm:p-8">
              <h2 className="text-lg font-semibold text-white">Clean metadata</h2>

              {pdf ? (
                <p className="mt-4 text-sm leading-6 text-slate-400">
                  Clears Title, Author, Subject, Keywords, Creator, Producer, Creation Date, and
                  Modification Date, plus any XMP metadata packet, then saves a new PDF with the
                  same pages and content.
                </p>
              ) : (
                <p className="mt-4 text-sm leading-6 text-slate-400">Add a PDF to inspect its metadata.</p>
              )}

              <button
                className="mt-6 w-full rounded-full bg-gradient-to-r from-teal-500 via-cyan-500 to-emerald-400 px-6 py-3 text-sm font-semibold text-[#04120f] shadow-xl shadow-teal-500/20 transition hover:-translate-y-0.5 hover:shadow-teal-500/30 disabled:cursor-not-allowed disabled:opacity-60 disabled:hover:translate-y-0"
                disabled={!pdf || isBusy}
                onClick={cleanMetadata}
                type="button"
              >
                {phase === "processing" ? "Cleaning..." : "Clean Metadata"}
              </button>

              <div className="mt-5 space-y-3">
                {phase === "preparing" ? <ProcessingState subtitle="Reading your PDF" title="Preparing" /> : null}
                {phase === "processing" ? (
                  <ProcessingState subtitle="Clearing metadata locally" title="Cleaning" />
                ) : null}
                {phase === "error" && errorMessage ? (
                  <ErrorCard message={errorMessage} title="Something went wrong" />
                ) : null}
              </div>
            </div>
          </aside>
        </div>
      )}
    </section>
  );
}
